# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unrelated_type_equality_checks: ignore
  plugins:
    - custom_lint
linter:
  rules:
    avoid_empty_else: true
    camel_case_types: true
    empty_catches: true
    constant_identifier_names: true
    control_flow_in_finally: true
    directives_ordering: true
    file_names: true
    implementation_imports: true
    library_prefixes: true
    lines_longer_than_80_chars: true
    non_constant_identifier_names: true
    prefer_typing_uninitialized_variables: true
    sort_constructors_first: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    avoid_print: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    unawaited_futures: true
    no_self_assignments: true 
    use_enums: true
    avoid_unused_constructor_parameters: true
    unnecessary_lambdas: true
    prefer_const_constructors: true
    always_use_package_imports: true
    prefer_final_fields: true
    annotate_overrides: true
    sort_pub_dependencies: true
    avoid_single_cascade_in_expression_statements: true
    prefer_const_declarations: true

dart_code_metrics:
  metrics-exclude:
    - test/**

  rules:
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - always-remove-listener